//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSX.Properties {
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Resources {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMSX.Properties.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage Bed {
      get {
        object obj = ResourceManager.GetObject("Bed", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage Biopsy {
      get {
        object obj = ResourceManager.GetObject("Biopsy", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage Calendar {
      get {
        object obj = ResourceManager.GetObject("Calendar", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage Diagnosy {
      get {
        object obj = ResourceManager.GetObject("Diagnosy", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
    /// </summary>
    internal static System.Drawing.Icon Icon {
      get {
        object obj = ResourceManager.GetObject("Icon", resourceCulture);
        return ((System.Drawing.Icon)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage Key {
      get {
        object obj = ResourceManager.GetObject("Key", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Logo {
      get {
        object obj = ResourceManager.GetObject("Logo", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage Microscope {
      get {
        object obj = ResourceManager.GetObject("Microscope", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage Pallete {
      get {
        object obj = ResourceManager.GetObject("Pallete", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage Password {
      get {
        object obj = ResourceManager.GetObject("Password", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage User {
      get {
        object obj = ResourceManager.GetObject("User", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage Users {
      get {
        object obj = ResourceManager.GetObject("Users", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }
  }
}
